//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFollowMe.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("${TopicPrefix}/left/image_rect")]
        public string DetectionImage {
            get {
                return ((string)(this["DetectionImage"]));
            }
            set {
                this["DetectionImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("${TopicPrefix}/follow_me/enable")]
        public string EnableTopic {
            get {
                return ((string)(this["EnableTopic"]));
            }
            set {
                this["EnableTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("${TopicPrefix}/follow_me/bounding_boxes")]
        public string BoundingBoxesTopic {
            get {
                return ((string)(this["BoundingBoxesTopic"]));
            }
            set {
                this["BoundingBoxesTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("${TopicPrefix}/follow_me/target_bounding_box")]
        public string TargetBoundingBoxTopic {
            get {
                return ((string)(this["TargetBoundingBoxTopic"]));
            }
            set {
                this["TargetBoundingBoxTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("${TopicPrefix}/follow_me/target_position")]
        public string TargetPositionTopic {
            get {
                return ((string)(this["TargetPositionTopic"]));
            }
            set {
                this["TargetPositionTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("${TopicPrefix}/follow_me/set_target")]
        public string SetTargetTopic {
            get {
                return ((string)(this["SetTargetTopic"]));
            }
            set {
                this["SetTargetTopic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("${TopicPrefix}/right/camera_info")]
        public string CameraInfoTopic {
            get {
                return ((string)(this["CameraInfoTopic"]));
            }
            set {
                this["CameraInfoTopic"] = value;
            }
        }
    }
}
